#!/usr/bin/env bash

echo - Making sure Build dir exists
mkdir bin 2> /dev/null

echo - Building VideoTest
gcc -o bin/videotest videotest.c `pkg-config --cflags --libs opencv`

echo - Building ImageTest
gcc -o bin/imagetest imagetest.c `pkg-config --cflags --libs opencv`

echo - Building Custom Tracking
gcc -o bin/video_cascade video_cascade.c `pkg-config --cflags --libs opencv`
gcc -o bin/image_cascade image_cascade.c `pkg-config --cflags --libs opencv`

echo Built!
